/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteRouteImport } from './routes/$slug/route'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as SlugManifestDotwebmanifestRouteImport } from './routes/$slug/manifest[.]webmanifest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRouteRoute = SlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugManifestDotwebmanifestRoute =
  SlugManifestDotwebmanifestRouteImport.update({
    id: '/manifest.webmanifest',
    path: '/manifest.webmanifest',
    getParentRoute: () => SlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteRouteWithChildren
  '/$slug/manifest.webmanifest': typeof SlugManifestDotwebmanifestRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug/manifest.webmanifest': typeof SlugManifestDotwebmanifestRoute
  '/$slug': typeof SlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteRouteWithChildren
  '/$slug/manifest.webmanifest': typeof SlugManifestDotwebmanifestRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$slug' | '/$slug/manifest.webmanifest' | '/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$slug/manifest.webmanifest' | '/$slug'
  id: '__root__' | '/' | '/$slug' | '/$slug/manifest.webmanifest' | '/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRouteRoute: typeof SlugRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/manifest.webmanifest': {
      id: '/$slug/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/$slug/manifest.webmanifest'
      preLoaderRoute: typeof SlugManifestDotwebmanifestRouteImport
      parentRoute: typeof SlugRouteRoute
    }
  }
}

interface SlugRouteRouteChildren {
  SlugManifestDotwebmanifestRoute: typeof SlugManifestDotwebmanifestRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

const SlugRouteRouteChildren: SlugRouteRouteChildren = {
  SlugManifestDotwebmanifestRoute: SlugManifestDotwebmanifestRoute,
  SlugIndexRoute: SlugIndexRoute,
}

const SlugRouteRouteWithChildren = SlugRouteRoute._addFileChildren(
  SlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRouteRoute: SlugRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
