/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteRouteImport } from './routes/$slug/route'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as SlugAccountRouteImport } from './routes/$slug/account'
import { Route as SlugAddCarRouteImport } from './routes/$slug/add-car'
import { Route as SlugBookRouteImport } from './routes/$slug/book'
import { Route as SlugBookingsRouteImport } from './routes/$slug/bookings'
import { Route as SlugCarRouteImport } from './routes/$slug/car'
import { Route as SlugHomeRouteImport } from './routes/$slug/home'
import { Route as SlugIconDotsvgRouteImport } from './routes/$slug/icon[.]svg'
import { Route as SlugManifestDotwebmanifestRouteImport } from './routes/$slug/manifest[.]webmanifest'
import { Route as SlugRequestedRouteImport } from './routes/$slug/requested'
import { Route as SlugResetPasswordRouteImport } from './routes/$slug/reset-password'
import { Route as SlugSignUpRouteImport } from './routes/$slug/sign-up'
import { Route as SlugTodayRouteImport } from './routes/$slug/today'
import { Route as SlugWelcomeRouteImport } from './routes/$slug/welcome'
import { Route as SlugInvoiceJobIdRouteImport } from './routes/$slug/invoice.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRouteRoute = SlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugAccountRoute = SlugAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugAddCarRoute = SlugAddCarRouteImport.update({
  id: '/add-car',
  path: '/add-car',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugBookRoute = SlugBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugBookingsRoute = SlugBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugCarRoute = SlugCarRouteImport.update({
  id: '/car',
  path: '/car',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugHomeRoute = SlugHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugIconDotsvgRoute = SlugIconDotsvgRouteImport.update({
  id: '/icon.svg',
  path: '/icon.svg',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugManifestDotwebmanifestRoute =
  SlugManifestDotwebmanifestRouteImport.update({
    id: '/manifest.webmanifest',
    path: '/manifest.webmanifest',
    getParentRoute: () => SlugRouteRoute,
  } as any)
const SlugRequestedRoute = SlugRequestedRouteImport.update({
  id: '/requested',
  path: '/requested',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugResetPasswordRoute = SlugResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugSignUpRoute = SlugSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugTodayRoute = SlugTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugWelcomeRoute = SlugWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => SlugRouteRoute,
} as any)
const SlugInvoiceJobIdRoute = SlugInvoiceJobIdRouteImport.update({
  id: '/invoice/$jobId',
  path: '/invoice/$jobId',
  getParentRoute: () => SlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteRouteWithChildren
  '/$slug/account': typeof SlugAccountRoute
  '/$slug/add-car': typeof SlugAddCarRoute
  '/$slug/book': typeof SlugBookRoute
  '/$slug/bookings': typeof SlugBookingsRoute
  '/$slug/car': typeof SlugCarRoute
  '/$slug/home': typeof SlugHomeRoute
  '/$slug/icon.svg': typeof SlugIconDotsvgRoute
  '/$slug/manifest.webmanifest': typeof SlugManifestDotwebmanifestRoute
  '/$slug/requested': typeof SlugRequestedRoute
  '/$slug/reset-password': typeof SlugResetPasswordRoute
  '/$slug/sign-up': typeof SlugSignUpRoute
  '/$slug/today': typeof SlugTodayRoute
  '/$slug/welcome': typeof SlugWelcomeRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/invoice/$jobId': typeof SlugInvoiceJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug/account': typeof SlugAccountRoute
  '/$slug/add-car': typeof SlugAddCarRoute
  '/$slug/book': typeof SlugBookRoute
  '/$slug/bookings': typeof SlugBookingsRoute
  '/$slug/car': typeof SlugCarRoute
  '/$slug/home': typeof SlugHomeRoute
  '/$slug/icon.svg': typeof SlugIconDotsvgRoute
  '/$slug/manifest.webmanifest': typeof SlugManifestDotwebmanifestRoute
  '/$slug/requested': typeof SlugRequestedRoute
  '/$slug/reset-password': typeof SlugResetPasswordRoute
  '/$slug/sign-up': typeof SlugSignUpRoute
  '/$slug/today': typeof SlugTodayRoute
  '/$slug/welcome': typeof SlugWelcomeRoute
  '/$slug': typeof SlugIndexRoute
  '/$slug/invoice/$jobId': typeof SlugInvoiceJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteRouteWithChildren
  '/$slug/account': typeof SlugAccountRoute
  '/$slug/add-car': typeof SlugAddCarRoute
  '/$slug/book': typeof SlugBookRoute
  '/$slug/bookings': typeof SlugBookingsRoute
  '/$slug/car': typeof SlugCarRoute
  '/$slug/home': typeof SlugHomeRoute
  '/$slug/icon.svg': typeof SlugIconDotsvgRoute
  '/$slug/manifest.webmanifest': typeof SlugManifestDotwebmanifestRoute
  '/$slug/requested': typeof SlugRequestedRoute
  '/$slug/reset-password': typeof SlugResetPasswordRoute
  '/$slug/sign-up': typeof SlugSignUpRoute
  '/$slug/today': typeof SlugTodayRoute
  '/$slug/welcome': typeof SlugWelcomeRoute
  '/$slug/': typeof SlugIndexRoute
  '/$slug/invoice/$jobId': typeof SlugInvoiceJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/$slug/account'
    | '/$slug/add-car'
    | '/$slug/book'
    | '/$slug/bookings'
    | '/$slug/car'
    | '/$slug/home'
    | '/$slug/icon.svg'
    | '/$slug/manifest.webmanifest'
    | '/$slug/requested'
    | '/$slug/reset-password'
    | '/$slug/sign-up'
    | '/$slug/today'
    | '/$slug/welcome'
    | '/$slug/'
    | '/$slug/invoice/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug/account'
    | '/$slug/add-car'
    | '/$slug/book'
    | '/$slug/bookings'
    | '/$slug/car'
    | '/$slug/home'
    | '/$slug/icon.svg'
    | '/$slug/manifest.webmanifest'
    | '/$slug/requested'
    | '/$slug/reset-password'
    | '/$slug/sign-up'
    | '/$slug/today'
    | '/$slug/welcome'
    | '/$slug'
    | '/$slug/invoice/$jobId'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/$slug/account'
    | '/$slug/add-car'
    | '/$slug/book'
    | '/$slug/bookings'
    | '/$slug/car'
    | '/$slug/home'
    | '/$slug/icon.svg'
    | '/$slug/manifest.webmanifest'
    | '/$slug/requested'
    | '/$slug/reset-password'
    | '/$slug/sign-up'
    | '/$slug/today'
    | '/$slug/welcome'
    | '/$slug/'
    | '/$slug/invoice/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRouteRoute: typeof SlugRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/account': {
      id: '/$slug/account'
      path: '/account'
      fullPath: '/$slug/account'
      preLoaderRoute: typeof SlugAccountRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/add-car': {
      id: '/$slug/add-car'
      path: '/add-car'
      fullPath: '/$slug/add-car'
      preLoaderRoute: typeof SlugAddCarRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/book': {
      id: '/$slug/book'
      path: '/book'
      fullPath: '/$slug/book'
      preLoaderRoute: typeof SlugBookRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/bookings': {
      id: '/$slug/bookings'
      path: '/bookings'
      fullPath: '/$slug/bookings'
      preLoaderRoute: typeof SlugBookingsRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/car': {
      id: '/$slug/car'
      path: '/car'
      fullPath: '/$slug/car'
      preLoaderRoute: typeof SlugCarRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/home': {
      id: '/$slug/home'
      path: '/home'
      fullPath: '/$slug/home'
      preLoaderRoute: typeof SlugHomeRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/icon.svg': {
      id: '/$slug/icon.svg'
      path: '/icon.svg'
      fullPath: '/$slug/icon.svg'
      preLoaderRoute: typeof SlugIconDotsvgRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/manifest.webmanifest': {
      id: '/$slug/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/$slug/manifest.webmanifest'
      preLoaderRoute: typeof SlugManifestDotwebmanifestRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/requested': {
      id: '/$slug/requested'
      path: '/requested'
      fullPath: '/$slug/requested'
      preLoaderRoute: typeof SlugRequestedRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/reset-password': {
      id: '/$slug/reset-password'
      path: '/reset-password'
      fullPath: '/$slug/reset-password'
      preLoaderRoute: typeof SlugResetPasswordRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/sign-up': {
      id: '/$slug/sign-up'
      path: '/sign-up'
      fullPath: '/$slug/sign-up'
      preLoaderRoute: typeof SlugSignUpRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/today': {
      id: '/$slug/today'
      path: '/today'
      fullPath: '/$slug/today'
      preLoaderRoute: typeof SlugTodayRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/welcome': {
      id: '/$slug/welcome'
      path: '/welcome'
      fullPath: '/$slug/welcome'
      preLoaderRoute: typeof SlugWelcomeRouteImport
      parentRoute: typeof SlugRouteRoute
    }
    '/$slug/invoice/$jobId': {
      id: '/$slug/invoice/$jobId'
      path: '/invoice/$jobId'
      fullPath: '/$slug/invoice/$jobId'
      preLoaderRoute: typeof SlugInvoiceJobIdRouteImport
      parentRoute: typeof SlugRouteRoute
    }
  }
}

interface SlugRouteRouteChildren {
  SlugAccountRoute: typeof SlugAccountRoute
  SlugAddCarRoute: typeof SlugAddCarRoute
  SlugBookRoute: typeof SlugBookRoute
  SlugBookingsRoute: typeof SlugBookingsRoute
  SlugCarRoute: typeof SlugCarRoute
  SlugHomeRoute: typeof SlugHomeRoute
  SlugIconDotsvgRoute: typeof SlugIconDotsvgRoute
  SlugManifestDotwebmanifestRoute: typeof SlugManifestDotwebmanifestRoute
  SlugRequestedRoute: typeof SlugRequestedRoute
  SlugResetPasswordRoute: typeof SlugResetPasswordRoute
  SlugSignUpRoute: typeof SlugSignUpRoute
  SlugTodayRoute: typeof SlugTodayRoute
  SlugWelcomeRoute: typeof SlugWelcomeRoute
  SlugIndexRoute: typeof SlugIndexRoute
  SlugInvoiceJobIdRoute: typeof SlugInvoiceJobIdRoute
}

const SlugRouteRouteChildren: SlugRouteRouteChildren = {
  SlugAccountRoute: SlugAccountRoute,
  SlugAddCarRoute: SlugAddCarRoute,
  SlugBookRoute: SlugBookRoute,
  SlugBookingsRoute: SlugBookingsRoute,
  SlugCarRoute: SlugCarRoute,
  SlugHomeRoute: SlugHomeRoute,
  SlugIconDotsvgRoute: SlugIconDotsvgRoute,
  SlugManifestDotwebmanifestRoute: SlugManifestDotwebmanifestRoute,
  SlugRequestedRoute: SlugRequestedRoute,
  SlugResetPasswordRoute: SlugResetPasswordRoute,
  SlugSignUpRoute: SlugSignUpRoute,
  SlugTodayRoute: SlugTodayRoute,
  SlugWelcomeRoute: SlugWelcomeRoute,
  SlugIndexRoute: SlugIndexRoute,
  SlugInvoiceJobIdRoute: SlugInvoiceJobIdRoute,
}

const SlugRouteRouteWithChildren = SlugRouteRoute._addFileChildren(
  SlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRouteRoute: SlugRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
