/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugManifestDotwebmanifestRouteImport } from './routes/$slug/manifest[.]webmanifest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugManifestDotwebmanifestRoute =
  SlugManifestDotwebmanifestRouteImport.update({
    id: '/$slug/manifest.webmanifest',
    path: '/$slug/manifest.webmanifest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug/manifest.webmanifest': typeof SlugManifestDotwebmanifestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug/manifest.webmanifest': typeof SlugManifestDotwebmanifestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug/manifest.webmanifest': typeof SlugManifestDotwebmanifestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$slug/manifest.webmanifest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$slug/manifest.webmanifest'
  id: '__root__' | '/' | '/$slug/manifest.webmanifest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugManifestDotwebmanifestRoute: typeof SlugManifestDotwebmanifestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/manifest.webmanifest': {
      id: '/$slug/manifest.webmanifest'
      path: '/$slug/manifest.webmanifest'
      fullPath: '/$slug/manifest.webmanifest'
      preLoaderRoute: typeof SlugManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugManifestDotwebmanifestRoute: SlugManifestDotwebmanifestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
